Error summary
cds-snc/gcds-components pull request #144
Opened 2023-04-17 13:26 UTC by ethanWallace

# Summary | Résumé

Add `gcds-error-summary` component to component library.

## Use

```html
<gcds-error-summary
  listen="true"        // boolean
  error-links=""      // string/object
  heading=""          // string
  sub-heading=""  // string
>
</gcds-error-summary>
```

### Listen

Using the `listen` attribute will listen for the `gcdsError` event and generate/display the error summary list when the parent form submits.

### Error-links

Use the `error-links` to render the error list without using event listeners. Pass a string or object formatted like the example below to render the list.
```
{
  "href": "Error message",
  "href": "Error message"
}
```

### Heading

To customize the error summary heading, pass a string to the `heading` attribute.

### Sub-heading

To customize the sub-heading, pass a string to the `sub-heading` attribute.

## **Note: This pull request uses the tokens from https://github.com/cds-snc/gcds-tokens/pull/112**

2023-04-24 22:14 UTC, melaniebmn commented on packages/web/src/components/gcds-error-summary/gcds-error-summary.tsx
> +      for (var id in this.errorLinksObject) {
Can we avoid using `var` and use `let` or `const` instead?

2023-04-24 22:17 UTC, melaniebmn commented on packages/web/src/components/gcds-error-summary/gcds-error-summary.tsx
> +            }
Could we replace this with `{heading ?? i18n[lang].heading}`?

2023-04-24 22:17 UTC, melaniebmn commented on packages/web/src/components/gcds-error-summary/gcds-error-summary.tsx
> +            }
Could we replace this with `{subHeading ?? i18n[lang].subheading}`?

2023-04-24 22:26 UTC, melaniebmn requested changes
Can the error summary links scroll to the label for each field instead of the input field itself? I think that would be a slightly nicer interaction.

Aside from that, a couple of small comments but overall it looks great, nice work!

2023-04-25 13:03 UTC, ethanWallace commented
> Can the error summary links scroll to the label for each field instead of the input field itself? I think that would be a slightly nicer interaction.

Good idea! I will look at adding this!

2023-04-25 14:56 UTC, melaniebmn approved these changes
LGTM!

2023-04-25 15:17 UTC, merged