Add overview + playground pages for header and footer stories
cds-snc/gcds-components pull request #283
Opened 2023-09-07 19:54 UTC by ethanWallace

# Summary | Résumé

Add the overview and playground storybook pages for the `gcds-header` and `gcds-footer`.

2023-09-07 22:34 UTC, melaniebmn commented on packages/web/src/components/gcds-footer/stories/gcds-footer.stories.tsx
> +  lang: 'en'
Can you add `display: 'compact'` here? It's currently showing up as `display="undefined"` in the code preview. Or if `compact` is supposed to be the default value, can you add it as the default value? Right now we don't have a default defined for `display`.

2023-09-07 22:39 UTC, melaniebmn commented on packages/web/src/components/gcds-header/stories/overview.mdx
> +### Slots
Could we maybe have an extra story here that shows all slots at once? Just so it's easier for the user to understand the order. For example, the menu slot is before the breadcrumbs slot, etc.

2023-09-07 22:41 UTC, melaniebmn requested changes
Two small comments, otherwise looks good!

2023-09-11 19:55 UTC, melaniebmn commented on packages/web/src/components/gcds-footer/gcds-footer.tsx
> +  @Prop({ reflect: true, mutable: true }) display: 'compact' | 'full' =
Should we mark this prop as optional?

2023-09-11 19:56 UTC, melaniebmn approved these changes
Added one more question, but feel free to merge if you disagree :)

2023-09-11 20:12 UTC, ethanWallace commented on packages/web/src/components/gcds-footer/gcds-footer.tsx
> +  @Prop({ reflect: true, mutable: true }) display: 'compact' | 'full' =
Good point, I will do that

2023-09-11 20:45 UTC, melaniebmn approved these changes
LGTM

2023-09-11 21:06 UTC, merged