Add wrapped prop for conditional render to fix slot hydration issue
cds-snc/gcds-components pull request #367
Opened 2024-01-10 15:57 UTC by ethanWallace

# Summary | Résumé

When using the experimental SSR package, a hydration error would occur when a GCDS component was slotted into another GCDS component. This was happening since the `GcdsWrapper` wraps each  GCDS component when used causing conflicts in the render.  This can be seen with the breadcrumbs, top-nav and side-nav components using https://github.com/ethanWallace/components-ssr-test.

## Solution

Added logic to add a `wrapped` prop into the rendering to prevent a `GcdsWrapper` from being placed inside another `GcdsWrapper`. The new prop is eventually removed before final render so it doesn't display on the component. These props should only be passed to GCDS components and avoid any other component.

2024-01-10 18:50 UTC, daine commented
I'm for this fix - appreciate the work put in!
Do we know if there are any side effects of this? Does it take longer to render?

2024-01-10 19:23 UTC, ethanWallace commented
> Do we know if there are any side effects of this? Does it take longer to render?

I honestly can't say. Before the developer would have to manually wrap our components in `GcdsWrapper` but we are trying to just build that in and I can't say if the `GcdsWrapper` would cause any issues with other libraries.

2024-01-10 23:30 UTC, daine commented
What do you think about doing `wrap` instead of `wrapped`? 

I like it because it's simple easy to understand -- `wrapped` seems to mean "this is already wrapped so **_do not_** wrap it" vs `wrap` which means "wrap this".

2024-01-11 00:07 UTC, melaniebmn commented on packages/ssr/scripts/utils.ts
> +      for (let x = 0; x< props.children.length; x++) {
You could simplify the structure a little bit if you use a map function for the array iteration instead.

2024-01-11 00:09 UTC, melaniebmn requested changes
One code improvement suggestion, but otherwise looks good. Thanks for looking into this and working on a fix!

2024-01-11 14:13 UTC, ethanWallace commented
> what do you think about doing `wrap` instead of `wrapped`?
> 
> I like it because it's simple easy to understand -- `wrapped` seems to mean "this is already wrapped so **_do not_** wrap it" vs `wrap` which means "wrap this".

Wrapped is the more accurate name. The new prop is only applied to the component and it's children when a component is rendered with `GcdsWrapper` so it is wrapped and now uses that prop to prevent rendering another `GcdsWrapper` inside the first one.

2024-01-11 16:11 UTC, daine commented
> > what do you think about doing `wrap` instead of `wrapped`?
> > I like it because it's simple easy to understand -- `wrapped` seems to mean "this is already wrapped so **_do not_** wrap it" vs `wrap` which means "wrap this".
> 
> Wrapped is the more accurate name. The new prop is only applied to the component and it's children when a component is rendered with `GcdsWrapper` so it is wrapped and now uses that prop to prevent rendering another `GcdsWrapper` inside the first one.

I was attempting to mean the opposite - using property names that require a detailed explanation tends to introduce more cognitive load and bugs to a codebase which is the reason why I'm not a big fan of them. If we do `wrap` it would do the exact same thing (wrap it in `GcdsWrapper` because it is not yet wrapped, otherwise do not add a `GcdsWrapper`

2024-01-11 16:50 UTC, ethanWallace commented
I think we are splitting hairs by trying to figure out if we do the logic based off a true prop or a false prop. I do see issues with switching the logic up like how does the first element know to be wrapped but I can definitely switch the prop to a clearer name.

2024-01-11 17:01 UTC, daine commented
> I think we are splitting hairs by trying to figure out if we do the logic based off a true prop or a false prop. I do see issues with switching the logic up like how does the first element know to be wrapped but I can definitely switch the prop to a clearer name.

Thank you, let's give it a clearer name and hopefully we can remove the comments too for the self-explanatory parts once that's done!

2024-01-11 17:05 UTC, daine requested changes
Could we change `wrapped` to be more clear and concise?

Example:
```javascript
if( prop.isAlreadyWrapped ){
        <${toPascalCase(elementName)}WebComponent {...props}>
        {cloned}
        </${toPascalCase(elementName)}WebComponent>
}
return {
   <GcdsWrapper>
        <${toPascalCase(elementName)}WebComponent {...props}>
        {cloned}
        </${toPascalCase(elementName)}WebComponent>
   </GcdsWrapper>
}
```

2024-01-11 21:53 UTC, daine approved these changes
LGTM! Thanks for making the change

2024-01-12 00:35 UTC, melaniebmn approved these changes
LGTM

2024-01-12 13:23 UTC, merged