fix: Fixes identified in OCADU report (a11y and usability)
cds-snc/gcds-components pull request #446
Opened 2024-02-19 19:05 UTC by ethanWallace

# Summary | Résumé

Updates to the `gcds-card`, `gcds-footer` and `gcds-footer` components based on the OCADU report.

## Card changes

- https://github.com/cds-snc/design-gc-conception/issues/684 Add hidden "Tagged:" text to card tag
- Use `aria-describedby` to make sure tag is not missed if tabbing between focusable elements

## Footer changes

- Remove `aria-label`'s and use existing headings in `gcds-footer` to label landmarks with `aria-labelledby`

## Input changes

- Change `autocomplete` property from `on  | off` to accept any `string`

2024-02-20 16:27 UTC, melaniebmn requested changes
Code looks good, but Voiceover is not reading the card tags or the footer headings out to me.

2024-02-20 19:26 UTC, ethanWallace commented
> Code looks good, but Voiceover is not reading the card tags or the footer headings out to me.

Is it not giving any additional options to open a more content menu when highlighting the card heading/links?

How are you trying to read the headings in the footer?

2024-02-21 17:56 UTC, daine commented
I tested the voiceover changes for the Card component.

I added an additional card for my testing (which you will see in the video below). Navigating to a Card component with a link doesn't automatically say the tag for me, but it does give me an option to bring up the `more content menu`. Doing so on the first card pops up a voice over utility that says `description, Tagged: Core`.

Not sure if I'm not great at navigating with a11y but it skipped my "Just a plain card", which is a card component with the `href` omitted. Pressing tab moved my cursor from the card in the existing group "Link card number 3" to the next card link located in a different group, "Action card number 1". I used the arrow keys to try and find my way to "Just a plain card" and that worked, but I had to use my mouse to scroll to the element since it wasn't in the center of my screen.

Using arrow keys to find "Just a plain card" navigated through the tag, and it also read the heading this way: `heading level 4, Just a plain card, description, Tagged: Test`. I noticed it automatically read the tag and I didn't have to bring up a `more content menu`
 
https://github.com/cds-snc/gcds-components/assets/916044/35972b40-9cae-4ba5-b4df-df2514ccb9f7

2024-02-21 18:16 UTC, daine commented
I tested the voiceover changes for the footer component. I added audio to this screen recording as I mentioned when I switch to arrow keys.

Looks like it's reading the names for me.

https://github.com/cds-snc/gcds-components/assets/916044/ffd6e9f8-0769-4da6-93ed-201fab0c5b95

2024-02-21 18:23 UTC, daine commented
I tested the input component to accomodate the autocomplete functionality.

I tried by testing it with a **First Name**

I tried by testing it with a **Last Name**
```javascript
        <gcds-input
          input-id="form-last-name"
          label="Last Name "
          hint="Please enter your last name."
          autocomplete="family-name"
          required
        ></gcds-input>
```

2024-02-21 18:42 UTC, daine approved these changes
I added my testing in comments to this PR.
I confirm that I've tested the three components and they seem to do what we intend for them to do.

I admit I'm not quite sure about the navigation, especially regarding the Card component, but I am approving this PR since I'm able to see the fix using Voiceover on my Macbook.

Approving the code, tests, and functionality of the following
- ✅ Card component reading tags on a screen reader
- ✅ Footer component reading name of the navigational element
- ✅ Input component having the ability to add string names for autocomplete, and having those a11y strings actually autocomplete on a form

Thanks for this, @ethanWallace. Great job!

2024-02-21 19:45 UTC, melaniebmn approved these changes
Ship it! 🥇

2024-02-22 16:59 UTC, merged