refactor: integrate gcds-link into existing components
cds-snc/gcds-components pull request #454
Opened 2024-02-22 22:48 UTC by melaniebmn

# Summary | Résumé

Integrate `gcds-link` component into existing components.

2024-02-23 01:06 UTC, daine requested changes
Looks git! Just a small nit on an extra line

2024-02-23 01:06 UTC, daine commented on packages/web/src/components/gcds-footer/gcds-footer.tsx
> +
```suggestion
```

2024-02-23 13:26 UTC, ethanWallace approved these changes
LGTM

2024-02-26 15:42 UTC, daine approved these changes
LGTM!

2024-02-26 22:24 UTC, merged