feat: add tag prop to gcds-sr-only component
cds-snc/gcds-components pull request #484
Opened 2024-03-25 15:37 UTC by melaniebmn

# Summary | Résumé

Added `tag` prop to `gcds-sr-only` to allow users to hide heading content as well as regular text content.

Integrated into the following, existing components:
- gcds-search
- gcds-file-uploader
- gcds-lang-toggle
- gcds-topic-menu
- gcds-header
- gcds-footer

[Dev board ticket](https://github.com/orgs/cds-snc/projects/38/views/1?layout=board&pane=issue&itemId=55606741)

2024-03-26 13:08 UTC, ethanWallace requested changes
Just one small thing

2024-03-26 14:47 UTC, daine commented on packages/web/src/components/gcds-sr-only/test/gcds-sr-only.spec.tsx
> +          </h2>
Would be nice if we have tests for the different tag types as well

2024-03-26 16:25 UTC, melaniebmn commented on packages/web/src/components/gcds-header/gcds-header.tsx
> +        <nav class="gcds-header__skip-to-nav" aria-label={i18n[this.lang].skip}>
Oh, you are right, I forgot about that. Got too into the landmark label zone :D Good flag!

2024-03-27 18:46 UTC, ethanWallace approved these changes
LGTM!

2024-03-27 20:05 UTC, merged