feat: consistent component events
cds-snc/gcds-components pull request #506
Opened 2024-04-23 18:47 UTC by ethanWallace

# Summary | Résumé

Went through the interactive components to make sure event naming and firing(emitting) behaviour was consistent between components. Also created a `emitEvent` utility function that will properly cancel cancelled events if either the gcds custom event or the native HTML event has been prevented.

## Changes

### `emitEvent` function

``` js
// Emit event with logic to cancel HTML events
// Returns false if event has been prevented
export const emitEvent = (
  e: Event,
  customEvent: EventEmitter,
  value?: unknown,
) => {
  const event = customEvent.emit(value);

  // Was the custom or native event interrupted
  if (event.defaultPrevented || e.defaultPrevented) {
    // Stop native HTML event in shadow-dom
    e.preventDefault();
    return false;
  }

  return true;
};
```

The `emitEvent` function allows the developer to cancel either the native HTML event or the gcds custom event in the `gcds-components`. An example would be using the `gcds-link` component, a developer would be able to use `e.preventDefault()` on either `click` or the `gcdsClick` event to stop the event from firing.

### General component changes

- removed extra `onFocus` private method from several components to clean up the code
- Renamed some events to `gcdsChnage` to be consistent between eachother. Example: `gcdsFileUploaderChange` is now `gcdsChange`
- Added `toggle` method to `gcds-details` to allow toggling by code. This will allow developers to create an accordion style pattern.
- Added relevant information to the details of custom events. Example:
  - `gcds-link` click event now contains the `href` of the link. 
  - `gcds-pagination type="list"` now contains `{ page: page number, href }` in event details

2024-04-23 23:06 UTC, melaniebmn approved these changes
Great refactor, thank you so much for doing this! Nice work :)

2024-04-24 16:25 UTC, daine requested changes
Nice work, thank you so much! Just have a few change requests and also some suggestions.

2024-04-24 16:25 UTC, daine commented on packages/web/src/components/gcds-checkbox/gcds-checkbox.tsx
> +  @Event() gcdsClick!: EventEmitter<void>;
Can we change the comment above to say "when the checkbox has been clicked."?

2024-04-24 16:25 UTC, daine commented on packages/web/src/components/gcds-checkbox/readme.md
> +| `gcdsClick`  | Emitted when the checkbox has focus.           | `CustomEvent<void>`   |
Same comment, this should say but I'm guessing this is pulled from the comment
```suggestion
| `gcdsClick`  | Emitted when the checkbox has been clicked.           | `CustomEvent<void>`   |
```

2024-04-24 16:25 UTC, daine commented on packages/web/src/components/gcds-file-uploader/readme.md
> +| `gcdsChange`     | Update value based on user selection.          | `CustomEvent<any>`    |
```suggestion
| `gcdsChange`     | Emitted when the user has made a file selection.          | `CustomEvent<any>`    |
```

Would this be a better description? I know this readme is autogenerated but we could change it in the comment

2024-04-24 16:25 UTC, daine commented on packages/web/src/utils/utils.ts
> +    // Stop native HTML event in shadow-dom
🌟 Super helpful comment documentation!

2024-04-24 16:25 UTC, daine commented on packages/web/src/components/gcds-select/readme.md
> +| `gcdsChange` | Update value based on user selection.           | `CustomEvent<any>`    |
```suggestion
| `gcdsChange` | Update value based on user selection.           | `CustomEvent<any>`    |
```
Could this be "Emitted when the select value has changed."? Just trying to match it with the other descriptions.

2024-04-24 16:25 UTC, daine commented on packages/web/src/components/gcds-select/gcds-select.tsx
> +            onInput={e => this.handleChange(e)}
This is super interesting. As we're doing an `onInput`, does it matter, or not, if we only have an external API for change `gcdsChange`? Will it make sense to be consistent and either also have `gcdsInput` or change `gcdsChange` to `gcdsInput`?

`onChange` occurs when the element loses focus and its value has changed
`onInput` occurs immediately when the element receives an input, or when its value has changed

2024-04-24 16:25 UTC, daine commented on packages/web/src/components/gcds-search/gcds-search.tsx
> +
I have a comment in this PR that also applies to this -- same situation about thinking about having a `gcdsInput` for consistency

2024-04-25 18:49 UTC, daine requested changes
Almost there, just a few cleanup on the comments and readme!

2024-04-25 18:49 UTC, daine commented on packages/web/src/components/gcds-file-uploader/gcds-file-uploader.tsx
> +   * Emitted when the user has uplaoded a file.
```suggestion
   * Emitted when the user has uploaded a file.
```

Sorry!!!

2024-04-25 18:49 UTC, daine commented on packages/web/src/components/gcds-input/gcds-input.tsx
> +   * Emitted when the input has received input.
While we're here updating documentation...
```suggestion
   * Emitted when the element has received input.
```
Open to others, just thought "input has received input" sounds a bit confusing

2024-04-25 18:49 UTC, daine commented on packages/angular/src/lib/stencil-generated/components.ts
> +   * Emitted when the input has received input.
Same comment as above
```suggestion
   * Emitted when the element has received input.
```

2024-04-25 18:49 UTC, daine commented on packages/angular/src/lib/stencil-generated/components.ts
> +   * Emitted when the select has received input.
Oh this is great too! Specifying "select"

2024-04-25 18:49 UTC, daine commented on packages/angular/src/lib/stencil-generated/components.ts
> +   * Emitted when the textarea has received input.
Is this meant for `gcdsInput`?
```suggestion
   * Emitted when the textarea value has changed.
```

2024-04-25 18:49 UTC, daine commented on packages/angular/src/lib/stencil-generated/components.ts
> +   * Emitted when the textarea has changed.
Wondering if they got swapped?
```suggestion
   * Emitted when the textarea has received input.
```

2024-04-25 19:18 UTC, daine approved these changes
LGTM! Thank you so much, great work!

2024-04-25 19:21 UTC, merged