fix: Remove rxjs events to avoid duplicate custom events in Angular
cds-snc/gcds-components pull request #566
Opened 2024-06-20 12:30 UTC by ethanWallace

# Summary | Résumé

With the `v0.22.0` release of the `@cdssnc/gcds-components-angular`, `@Outputs` were added to the generated angular components. Unfortunately this was now causing custom events like `gcdsClick` to be emitted twice.

To fix, I removed Stencil's implementation of events from `rxjs` to remove the duplicate emitted events.

## Example angular component

```
import {Component} from '@angular/core';

@Component({
  selector: 'app-click-me-gcds',
  template: ` <gcds-button type="button" (gcdsClick)="onClickMe()">Click me!</gcds-button>
    <gcds-pagination type="list" current-page="3" total-pages="20" (gcdsClick)="onClick($event)"></gcds-pagination>
`,
})
export class ClickMeGcdsComponent {
  clickMessage = '';

  onClickMe() {
    console.log('clicked')
  }
  onClick(event: any) {
    event.preventDefault();
    console.log(event.detail)
  }
}
```

Previously the `gcdsClick` would be emitted twice when either the button or pagination links were clicked. Now only one event is emitted.

2024-06-25 19:00 UTC, melaniebmn commented on utils/angular-output-target/src/generate-angular-component.ts
> +   */
Thanks for adding extra comments :)

2024-06-25 19:00 UTC, melaniebmn submitted a review, later dismissed
LGTM

2024-06-25 22:58 UTC, daine commented
FYI I'm still testing this -- should get to it by tonight :)

2024-06-26 19:06 UTC, daine commented on packages/angular/src/lib/stencil-generated/angular-component-lib/utils.ts
> + */
```suggestion
/**
 * GCDS Modification
 * Replaced 
 *     import { fromEvent } from 'rxjs'; 
 * From: https://github.com/ionic-team/stencil-ds-output-targets/blob/9524c1ce970770e01afb493c292f71a2fe61b14a/packages/angular-output-target/angular-component-lib/utils.ts#L3
 */
```

2024-06-26 19:19 UTC, daine requested changes
Works pretty well, I tested by using our npm package 0.22.1 to verify that the events were being emitted twice, and then tested this PR and I can confirm that it is no longer firing twice.

Hoping to add more info in the comments about the changes so I added some suggestions in line. Thanks @ethanWallace !

2024-06-26 19:19 UTC, daine commented on packages/angular/src/lib/stencil-generated/angular-component-lib/utils.ts
> + */
```suggestion
/**
 * GCDS modification
 * Replaced 
 *   fromEvent(el, eventName)
 * to
 *   new EventEmitter()
 * From: https://github.com/ionic-team/stencil-ds-output-targets/blob/9524c1ce970770e01afb493c292f71a2fe61b14a/packages/angular-output-target/angular-component-lib/utils.ts#L38
 */
```

2024-06-26 19:19 UTC, daine commented on utils/angular-output-target/angular-component-lib/utils.ts
> + */
Oops I commented on the generated file first sorry!

```suggestion
/**
 * GCDS Modification
 * Replaced 
 *     import { fromEvent } from 'rxjs'; 
 * From: https://github.com/ionic-team/stencil-ds-output-targets/blob/9524c1ce970770e01afb493c292f71a2fe61b14a/packages/angular-output-target/angular-component-lib/utils.ts#L3
 */
```

2024-06-26 19:19 UTC, daine commented on utils/angular-output-target/angular-component-lib/utils.ts
> + */
```suggestion
/**
 * GCDS modification
 * Replaced 
 *   fromEvent(el, eventName)
 * to
 *   new EventEmitter()
 * From: https://github.com/ionic-team/stencil-ds-output-targets/blob/9524c1ce970770e01afb493c292f71a2fe61b14a/packages/angular-output-target/angular-component-lib/utils.ts#L38
 */
```

2024-06-26 19:19 UTC, daine commented on utils/angular-output-target/src/generate-angular-component.ts
> +   */
```suggestion
  /**
   * GCDS modification
   * - Added conditional to add outputs
   */
```

2024-06-26 19:19 UTC, daine commented on utils/angular-output-target/src/generate-angular-component.ts
> +   * - Modify proxyOutouts to remove second parameter "this.el"
```suggestion
   * 
   * GCDS modifications
   * - Added `hasOutputs` logic to render outputs
   * - Modified proxyOutputs to remove second parameter `this.el`
   *      proxyOutputs(this, this.el, [${formattedOutputs}]);`
   *   From: https://github.com/ionic-team/stencil-ds-output-targets/blob/9524c1ce970770e01afb493c292f71a2fe61b14a/packages/angular-output-target/src/generate-angular-component.ts#L82
```

2024-06-27 15:52 UTC, merged