ci: add react ssr
cds-snc/gcds-components pull request #587
Opened 2024-07-19 22:29 UTC by daine

# Summary | Résumé

PR to add the react ssr package

2024-07-24 17:53 UTC, daine commented
Tested the CI run here for publishing:
https://github.com/daine/gcds-components/actions/runs/10071411555/job/27841892005
![Screenshot 2024-07-24 at 10 52 35 AM](https://github.com/user-attachments/assets/78a407f3-3515-4787-b600-5fcb389342f8)

I commented out everything else but the react-ssr package. It was successful, so I then tested that package on the NextJS PR and it works on dev and builds.

2024-07-26 12:22 UTC, ethanWallace requested changes
Just one small thing

2024-07-26 12:22 UTC, ethanWallace commented on packages/react-ssr/package.json
> +    "@cdssnc/gcds-components": "^0.22.0",
Can you up the web components package dependency version to the latest version? `0.22.2`

2024-07-29 12:47 UTC, ethanWallace submitted a review, later dismissed
LGTM

2024-07-29 19:18 UTC, melaniebmn approved these changes
LGTM - ship it! Wohoooo

2024-07-31 19:58 UTC, ethanWallace approved these changes
LGTM!

2024-07-31 20:31 UTC, merged