Feat 152 text input component
cds-snc/gcds-components pull request #6
Opened 2022-03-09 16:55 UTC by melaniebmn

# Summary | Résumé

Adding new input component, including error message, hint, and label.

Ticket: https://app.zenhub.com/workspaces/design-system-6100624a19f4cf000e46e458/issues/cds-snc/design-gc-conception/159

2022-03-10 15:49 UTC, ethanWallace requested changes
It's looking good! Just a few accessibility things to fix up and it should be good to go.

2022-03-10 18:33 UTC, ethanWallace commented
Was doing some further testing with the gcds-input component in an HTML form. Whenever I submit the form, the form doesn't receive the gcds-input's value. This is because the input is in the shadow DOM and the form can't see it. We will need to add a way for the component to pass that value to the form properly.

2022-03-10 22:06 UTC, melaniebmn commented on src/components/gcds-input/gcds-input.tsx
> +          aria-describedby={`label-for-${inputId} ${inputHint ? `hint-${inputId}` : ''} ${errorMessage ? `error-message-${inputId}` : ''}`}
Oh weird, I've been testing with VoiceOver and it's reading out the error message.
I'll check with you on Slack!

2022-03-11 05:03 UTC, melaniebmn commented on src/components/gcds-input/gcds-input.tsx
> +          aria-describedby={`label-for-${inputId} ${inputHint ? `hint-${inputId}` : ''} ${errorMessage ? `error-message-${inputId}` : ''}`}
This should be fixed now.

2022-03-14 18:41 UTC, melaniebmn commented on src/components/gcds-input/gcds-input.tsx
> +        <gcds-label
This should be fixed now.

2022-03-14 18:43 UTC, melaniebmn commented
> Was doing some further testing with the gcds-input component in an HTML form. Whenever I submit the form, the form doesn't receive the gcds-input's value. This is because the input is in the shadow DOM and the form can't see it. We will need to add a way for the component to pass that value to the form properly.

@ethanWallace everything should be fixed now. Could you please review it again?

2022-03-21 12:24 UTC, ethanWallace commented
One last thing to fix up. Currently the id given to the component will be on both the `<gcds-input>` and the `<input>` tag. Will need to make sure it doesn't appear on the parent tag.

2022-03-21 19:27 UTC, ethanWallace approved these changes

2022-03-21 20:17 UTC, merged