fix: Add prebuild script to react package
cds-snc/gcds-components pull request #692
Opened 2024-11-28 14:08 UTC by ethanWallace

# Summary | Résumé

Add a prebuild script that adds `// @ts-expect-error` to two files generated for the react package build. This will allow the react package to build.

2024-12-11 00:24 UTC, daine requested changes
Initial review - found a few things we can improve a little on, I'll still continue testing

2024-12-11 00:24 UTC, daine commented on packages/react/scripts/buildPatch.js
> +    path: path.join(
```suggestion
    filePath: path.join(
```

2024-12-11 00:24 UTC, daine commented on packages/react/scripts/buildPatch.js
Could we also change this to another name? `buildPatch` implies we're building a patch, but we're actually applying patches here within a pre-build script. Will `patchFiles.js` work? Or `patchScript.js`?

2024-12-11 00:24 UTC, daine commented on packages/react/scripts/buildPatch.js
> +});
Can we avoid nested callbacks to keep it simpler and avoid callback loops?
Can we also try and make it so it asynchronously just to make it more efficient? We can use either promises or async/await with `.map`?

2024-12-16 15:07 UTC, ethanWallace commented
Closing this pull request, work will continue in https://github.com/cds-snc/gcds-components/pull/709

2024-12-16 15:07 UTC, closed without merging